version: '3.8'

services:
  flask-app:
    build:
      context: ./flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: always

  nitro-api:
    build:
      context: ./nitro-api
    ports:
      - "3000:3000"
    environment:
      - FLASK_API_URL=http://flask-app:5000
    restart: always
    depends_on:
      - flask-app

